### ISSUE TITLE
Direct Video problem

### ISSUE THREAD

**Issue by sorgelig** [MiSTer-devel/Arcade-ATetris_MiSTer#1]
clk_hdmi must be >40MHz. In this particular core you can set it simply twice higher (57.272726).
Otherwise in direct video mode with scandoubler enabled video will have problems like absent audio over HDMI or absent the whole video.

**Comment by MrX-8B** [comment]
I'm thinking of fixing it right away and releasing it, but what should I do with the release date of the RBF file name?
Should I change it?

**Comment by sorgelig** [comment]
Release tomorrow :)

**Comment by MrX-8B** [comment]
roger :)

**Comment by alanswx** [comment]
I always release with a day earlier date because I know I am going to make mistakes

**Comment by MrX-8B** [comment]
I see :)

**Comment by MrX-8B** [comment]
Now that I've built and committed the RBF file, close it.
Thank you for your point.

**Comment by sorgelig** [comment]
Release date is hardcoded in the core, so you can see it in about dialog. So it's better not to cheat this way. It will be confusing to have one date in file name and another in about.

Btw, for better experience, for arcades using non-standard button names it's better to write name mapping (jn option in CONF_STR) - you can check the Genesis core for example. So Arcade will be ready to play without manual mapping.

**Comment by MrX-8B** [comment]
I understood. Refer to the Genesis Core.
